contractions = {"she'll": 'she will', 
"shouldn't've": 'should not have', 
"she'll've": 'she will have', 
"don't": 'do not', 
"should've": 'should have',
"won't": 'will not',
"who'll've": 'who will have',
"he's": 'he is',
"when's": 'when is',
"we've": 'we have',
"he'd": 'he had',
"ma'am": 'madam',
"y'all're": 'you all are',
"he'd've": 'he would have',
"how'd'y": 'how did you',
"shan't've": 'shall not have',
"haven't": 'have not',
"who's": 'who is',
"they'd": 'they would',
"oughtn't": 'ought not',
"you've": 'you have',
"she'd've": 'she would have',
"we'll": 'we will', 
"they've": 'they have', 
"mustn't've": 'must not have', 
"could've": 'could have', 
"what've": 'what have', 
"mustn't": 'must not', 
"isn't": 'is not', 
"it'll": 'it will', 
"i'll": 'i will', 
"why's": 'why is', 
"you'd": 'you would', 
"hasn't": 'has not', 
"they'll've": 'they will have', 
"we'd": 'we would', 
"he'll've": 'he will have', 
"shan't": 'shall not', 
"y'all'd've": 'you all would have', 
"there'd": 'there would', 
"needn't": 'need not', 
"o'clock": 'of the clock', 
"hadn't've": 'had not have', 
"wouldn't've": 'would not have', 
"there's": 'there is', 
"shouldn't": 'should not', 
"they'll": 'they will', 
"mightn't": 'might not', 
"you're": 'you are', 
"what'll": 'what will', 
"mightn't've": 'might not have', 
"hadn't": 'had not', 
"aren't": 'are not', 
"let's": 'let us', 
"wouldn't": 'would not', 
"i'd": 'i had', 
"weren't": 'were not', 
"would've": 'would have', 
"i'm": 'i am', 
"can't": 'cannot', 
"y'all": 'you all', 
"couldn't": 'could not', 
"how'll": 'how will', 
"doesn't": 'does not', 
"when've": 'when have', 
"how's": 'how is', 
"it's": 'it is', 
"y'all've": 'you all have', 
"how'd": 'how did', 
"we're": 'we are', 
"it'd": 'it had', 
"what're": 'what are', 
"i've": 'i have', 
"oughtn't've": 'ought not have', 
"what's": 'what is', 
"who'll": 'who will', 
"i'd've": 'i would have', 
"must've": 'must have', 
"they're": 'they are', 
"you'd've": 'you would have', 
"wasn't": 'was not', 
"it'll've": 'it will have', 
"couldn't've": 'could not have', 
"won't've": 'will not have', 
"so's": 'so is', 
"you'll've": 'you will have', 
"i'll've": 'i will have', 
"didn't": 'did not', 
"where've": 'where have', 
"it'd've": 'it would have', 
"who've": 'who have', 
"to've": 'to have', 
"where'd": 'where did', 
"where's": 'where is', 
"what'll've": 'what will have', 
"'cause": 'because', 
"might've": 'might have', 
"he'll": 'he will', 
"we'll've": 'we will have', 
"she'd": 'she had', 
"can't've": 'cannot have', 
"you'll": 'you will', 
"will've": 'will have', 
"she's": 'she is', 
"that's": 'that is'}